import type { Character, Location, Scene, Shot } from "@/domain/movie";

export function character(overrides: Partial<Character> = {}): Character {
  return { id: "character-elias", name: "Elias", age: 32, gender: "male", face: "angular", hair: "dark", height: "183 cm", build: "lean", wardrobe: [{ id: "coat", label: "winter", clothing: ["charcoal coat", "grey shirt"], shoes: "black boots", accessories: [], validFromSceneId: "scene-1", validToSceneId: null }], voice: { description: "warm baritone", speechPattern: "measured", provider: "openai", providerVoiceId: "cedar" }, personality: "persistent", backstory: "journalist", relationships: {}, referenceAssetIds: ["ref-face"], locks: { appearance: true, voice: true, outfit: true }, ...overrides };
}
export function location(overrides: Partial<Location> = {}): Location {
  return { id: "location-street", name: "West 46th", appearance: "snowy street", architecture: "pre-war", furniture: [], objectLayout: { phoneBooth: "north corner" }, defaultLighting: "cold sodium vapor", defaultWeather: "light snow", timeOfDay: "night", importantDetails: ["red awning"], referenceAssetIds: ["ref-street"], designLocked: true, ...overrides };
}
export function shot(id = "shot-1", dependencies: string[] = []): Shot {
  return { id, sceneId: "scene-1", sequence: Number(id.split("-").at(-1)) || 1, title: id, durationSeconds: 8, action: "Elias crosses the street", visualStyle: "grounded noir", camera: { shotSize: "medium", angle: "eye-level", lens: "50mm", movement: "tracking", framing: "center", fps: 24 }, lighting: "cold sodium vapor", audioContext: { cleanStart: true, speakers: [], silentCharacters: ["character-elias"], dialogue: [], ambience: ["winter street"], soundEffects: ["footsteps"], musicCue: null, forbidCarryOver: ["previous dialogue", "previous music"] }, continuity: { characterStates: { "character-elias": { locationId: "location-street", wardrobeId: "coat", heldProps: [], injuries: [], appearanceChanges: [], position: "south curb", emotionalState: "alert" } }, locationId: "location-street", locationState: { timeOfDay: "night", weather: "light snow", lighting: "cold sodium vapor", objectPositions: { phoneBooth: "north corner" } }, previousShotId: null, nextShotId: null, requiredReferences: ["ref-face","ref-street"], lockedValues: { "character-elias.face": "angular" } }, dependencies, generationPrompt: { sceneIntent: "cross street", modelId: "veo-3.1-fast-generate-preview", prompt: "Elias crosses a snowy street", negativeDirectives: [], referenceAssetIds: ["ref-face"], seed: 42 } };
}
export function scene(shots: Shot[] = [shot()]): Scene {
  return { id: "scene-1", actId: "act-1", sequenceId: "sequence-1", number: 1, title: "Cold trail", durationSeconds: shots.reduce((sum,item)=>sum+item.durationSeconds,0), locationId: "location-street", characterIds: ["character-elias"], action: "Elias follows a signal", emotionalBeat: "suspicion", lighting: "cold", sound: "street", music: null, timeOfDay: "night", weather: "light snow", continuityRequirements: ["same coat"], shots };
}
